{
    "I Wanna Run Away": "https://akanims.pages.dev/I%20Wanna%20Run%20Away%2Elua",
    "II belly": "https://akanims.pages.dev/ii_belly.lua",
    "Mini Dance 3": "https://akanims.pages.dev/mini_dance_3.lua",
    "hug1": "https://akanims.pages.dev/name_hug1.lua",
    "eating 2": "https://akanims.pages.dev/eating_2.lua",
    "sharp whos over there": "https://akanims.pages.dev/whos_over_there.lua",
    "sharp lay twerk 7.5": "https://akanims.pages.dev/lay_twerk_7.5.lua",
    "on the knees eating": "https://akanims.pages.dev/on_the_knees_eating.lua",
    "chapa": "https://akanims.pages.dev/chapa.lua",
    "hug short": "https://akanims.pages.dev/hug_short.lua",
    "RandomEmote": "https://akanims.pages.dev/randomemote.lua",
    "hypras jerkoff": "https://akanims.pages.dev/jerkoff.lua",
    "DANCE A": "https://akanims.pages.dev/dance_a.lua",
    "hypras facefuck": "https://akanims.pages.dev/nigger.lua",
    "DANCE B": "https://akanims.pages.dev/dance_b.lua",
    "Les": "https://akanims.pages.dev/les.lua",
    "Twerk": "https://akanims.pages.dev/Twerk%2Elua",
    "lightsaber peis (thin r15)": "https://akanims.pages.dev/lightsaber.lua",
    "lay down J2": "https://akanims.pages.dev/lay_down_j2.lua",
    "poodle me": "https://akanims.pages.dev/me.lua",
    "bark twerk": "https://akanims.pages.dev/bark.lua",
    "dance 28": "https://akanims.pages.dev/dance_28.lua",
    "throw it in a circle": "https://akanims.pages.dev/throw_it_in_a_circle.lua"
}